### ISSUE TITLE
Unknown File FOrmat

### ISSUE THREAD

**Issue by gokhancnr** [riazXrazor/udemy-dl#1]
Dear Riaz,

I'm having below:

![udemy-dl](https://cloud.githubusercontent.com/assets/7801580/25115415/c61beb8a-240e-11e7-8619-d3151a4e8628.jpg)

**Comment by riazXrazor** [comment]
Hi,
    Sorry for the late reply, i ws quite busy with other projects...i think udemy has changed some internal video api, m looking into it, will fix this ASAP.

Thank You.

**Comment by riazXrazor** [comment]
Hi gokhancnr, 
 i have fixed the issue and updated the npm package. :-)
Thank You.

**Comment by gokhancnr** [comment]
Hi Riaz,

Thank you very much.
