### ISSUE TITLE
Problem Resolution

### ISSUE THREAD

**Issue by lucasndv** [riazXrazor/udemy-dl#14]
Only working with 360p

Message:
Unknown video resolution

**Comment by riazXrazor** [comment]
may be the video is not available in other versions, but its listed in the site

**Comment by lucasndv** [comment]
Yes, Its in the site.
All resolutions, only download 360p

**Comment by davidhenley** [comment]
Same issue. Any fix to this? It's listed on the site as having 1080 and 720 but will only download in 480. The site DEFINITELY has 720 and 1080 versions available. It's not upscaled.
