### ISSUE TITLE
no resume option

### ISSUE THREAD

**Issue by tremkonzah** [riazXrazor/udemy-dl#15]
When i download my courses, and disconnected in the middle of download, **udl** doesn't able to resume, it just skip the file and download the next video courses.

And i notice too **udl** doesn't able to download courses content other than video

in original udemy-dl version, we able to resume and download all courses content (sadly original version disappear from github)

Thanks

**Comment by riazXrazor** [comment]
Hmm resume will think on that and about course contents I hv deliberately
kept it out for now, will soon put it in if it's required.

**Comment by tremkonzah** [comment]
Thanks 👍 

Resume feature would be great addition

**Comment by philerck** [comment]
download courses content would be also a great addition

**Comment by riazXrazor** [comment]
jst close the terminal, wen u start download the next time it should start from the last video.

**Comment by vivekkumar27june88** [comment]
@riazXrazor Closing terminal and starting again, does not solve this issue. Its starting from beginning not from where it was interrupted due to internet. am  I am using  version 2.
