### ISSUE TITLE
GUI version of Udemy-dl

### ISSUE THREAD

**Issue by riazXrazor** [riazXrazor/udemy-dl#18]
i am thinking of making a gui version of this tool, is it a good idea ?

**Comment by abhion** [comment]
yeah. that'd be great

**Comment by piedpiper-coder** [comment]
Good thinking ! Be proud of yourself.. 
Support Download Subtitles ?

**Comment by francaflavio** [comment]
It works.
https://github.com/FaisalUmair/udemy-downloader-gui

**Comment by riazXrazor** [comment]
@francaflavio cool i ws quite suprised at first, m checking it out too, any ways i've already started the dev process and i'll look at his source too, it will help me too, i'll try to improve on it then.

**Comment by piedpiper-coder** [comment]
Subtitle Files (.VTT) for Udemy Courses 

How to convert .vtt to .srt
https://www.youtube.com/watch?v=FkLUtRwxZXU

**Comment by riazXrazor** [comment]
![img_23122017_235848_0_20171224_000047709](https://user-images.githubusercontent.com/13194363/34328408-14c62ece-e905-11e7-8451-b57920436cb3.jpg)
This is how it's looking so far.

**Comment by riazXrazor** [comment]
@piedpiper-coder i hv added support to download subtitles too now 👍

**Comment by riazXrazor** [comment]
after a long time started to work on it again

**Comment by riazXrazor** [comment]
a pre-alpha version, its bit slow and unoptimized but its kind of a workable.
- windows version : https://drive.google.com/open?id=1kO0WCVuZGXbaEr6s7G_2azWLeNUTIvKK
- linux version: https://drive.google.com/open?id=1e2_R6Wf3buQALrFrJZckhYESuvtZwDS8
- mac version : https://drive.google.com/open?id=1Hrm9lelrprdaTKZdR8jjdU3Cvyldy3jK
