### ISSUE TITLE
Download from lecture X

### ISSUE THREAD

**Issue by mindOf-L** [riazXrazor/udemy-dl#19]
In other similar python scripts exists the option to download from lecture X. Could be possible to add this function? For example, I downloaded a course I purchased, but my computer slept like 15 minutes because of inactivity. I just want to download from the point the computer left.

**Comment by nikitashekhov** [comment]
+1. Ideally to show the list of sections and lectures before downloading.

**Comment by riazXrazor** [comment]
yup great suggestions, sorry work on cli is on hold for a while now m working on the GUI version for a while.

**Comment by riazXrazor** [comment]
@nikitashekhov i cn show that it will be long, would it be ok ?
