### ISSUE TITLE
Friendly file names

### ISSUE THREAD

**Issue by JC-JackClark** [riazXrazor/udemy-dl#2]
Hi, when a video section/video title contains the following characters (on windows):

< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)

The program hangs. Maybe a string replace on these characters?

Thanks,

**Comment by riazXrazor** [comment]
Hi Jack, 
           Thanks for your feed, you are right, will fix it ASAP.
Thanks,

**Comment by riazXrazor** [comment]
Hi Jack,
               i have pushed a fix and updated the npm package, plz can you confirm that the issue is fixed.
Thanks.

**Comment by JC-JackClark** [comment]
Thanks for fixing quickly, unfortunately, that didn't work with the course I tried.

I have created a pull request. I will close the issue regardless. (I haven't updated npm package)

Thanks,

**Comment by riazXrazor** [comment]
i was trying with the slugify, if that didn't work i was going to think something else, but you did it, thanks a ton.
