### ISSUE TITLE
download attachments

### ISSUE THREAD

**Issue by osazemeu** [riazXrazor/udemy-dl#23]
Module downloads videos correctly but attachments(html, zip) are excluded. Could you fix this in future versions?

**Comment by riazXrazor** [comment]
Hi osazemeu,
 i intentionally left the extra downloads, as m bit busy now days with work, will try to improve n add in future updates.
Thanks,
Riaz

**Comment by riazXrazor** [comment]
@osazemeu this feature has been added in 0.0.15 release.
