### ISSUE TITLE
Can't install from npm 

### ISSUE THREAD

**Issue by saitawngpha** [riazXrazor/udemy-dl#29]
Dear, 
I try to install like your guide. But I can't, I have got the error like below.
Please help, how to fix it?

![npm](https://user-images.githubusercontent.com/9567660/39562043-6f77663c-4ecf-11e8-8b3a-1e43a19ca4a6.png)

**Comment by riazXrazor** [comment]
@saitawngpha i have tried installing it , it worked fine, plz try again.

**Comment by saitawngpha** [comment]
@riazXrazor yes sir, will try again.

**Comment by saitawngpha** [comment]
I have tried installing it, but it doesn't work. I am still getting the same error. plz help.

**Comment by riazXrazor** [comment]
try running this command 
```npm config set strict-ssl false```
after that install the package.
