### ISSUE TITLE
possible to change format so lesson numbers are included?

### ISSUE THREAD

**Issue by vesper8** [riazXrazor/udemy-dl#30]
Currently this works fantastic but it is missing one thing IMO.. it doesn't number the lessons. It does number the folders and put the lessons in the sub-folders.. but the lessons themselves are not numbered like they are on the Udemy website so you end up not knowing the correct order to watch the lessons in

Is it possible to change this?

**Comment by riazXrazor** [comment]
Yup sure is, I'll see what I can do wit it.

**Comment by riazXrazor** [comment]
i hv released a new version with the update. check it out.

**Comment by vesper8** [comment]
awesome!! thanks a lot!
