### ISSUE TITLE
Company account - not able to log in

### ISSUE THREAD

**Issue by Utfard** [riazXrazor/udemy-dl#36]
Hi , 
I am using a company account, the course link looks like this : 
https://olp-uk.udemy.com/artificial-intelligence-az/
The downloader can not log in using this type of account.

**Comment by riazXrazor** [comment]
@Utfard sorry, i didnt kno there was a company account in udemy, well i dont hv one to test with, let me see wat i can do  about that.

**Comment by suksin** [comment]
@riazXrazor I am having the same issue too. I have login for 'Udemy for Business' with Single Sign-on, get the same error. Wondering if you have any solution for that...Thanks in advance.

**Comment by riazXrazor** [comment]
if anyone can provide me a company account credential den i can add support for company login too.

**Comment by jontavd** [comment]
Hello @riazXrazor if you wish, send me an email and we can work with my company account credential ...

**Comment by riazXrazor** [comment]
support added thanks to @Sab94

**Comment by deepakray184** [comment]
Hi Guys,
r u able to login using corporate account? After running the script the course loading part is taking a lot of time. I have access to entire Udemy courses from my corporate account. However It is working perfect from my personal account. Thanks In Advance !!
![error](https://user-images.githubusercontent.com/22987796/62526831-a61b8e00-b857-11e9-9927-ec88eadca146.JPG)
