### ISSUE TITLE
add sanitize-filename to package.json

### ISSUE THREAD

**Issue by tberghuis** [riazXrazor/udemy-dl#4]
Great module.

I had to install sanitize-filename globally for it to run.

**Comment by riazXrazor** [comment]
Hi tberghuis,
   Sorry for the issue during the last pull request he must hv missed to add the dependency to package.json.  i ws quite busy it slipped me too. i have added the dependency. 

Thanks for the complement :)

Thank You,
Riaz

**Comment by JC-JackClark** [comment]
Hi Riaz,

Apologies, rather new to node js, but now I know about package.json and dependencies!

Thanks for fixing!

Jack

**Comment by riazXrazor** [comment]
Hi Jack,
   Thats fine :) !! great to hear your better at node. your help was much appreciated. keep it up..

Thanks, 
Riaz
