### ISSUE TITLE
Courses List Feature

### ISSUE THREAD

**Issue by vikasnewports** [riazXrazor/udemy-dl#40]
Hello
first of all I would like to thank you for this great Repo ..
I want to request a feature in this script
Export/Download the Courses Name along with their URL 
is this possible ?

**Comment by riazXrazor** [comment]
Hi @vikasnewports,  its already there, wen ur download begins a folder called "udl-tmp" is created the a json file is created with courseID, which contains all the course name and url, u can check, i can add a command to export it out too as its already there.

**Comment by vikasnewports** [comment]
Thank you , what is that command

**Comment by riazXrazor** [comment]
use the command with an `-e` flag it should export it

**Comment by vikasnewports** [comment]
@riazXrazor i tried the following
udl -e -u -p
courses list not exported ... instead of export the list it show the list of courses to download... can you please explain how can i do it.. moreover GUI version's attachment is old please check

**Comment by riazXrazor** [comment]
try 
`udl -u youremail -p password -e`
it should work
BTW update to the latest version.

**Comment by riazXrazor** [comment]
![image](https://user-images.githubusercontent.com/13194363/51492152-c9f51600-1dd6-11e9-9a76-8c2abda6e222.png)
working on gui from scratch again with new UI, will be releasing soon

**Comment by vikasnewports** [comment]
@riazXrazor , thank you for response and I am using latest version. still the same error see the screen shot http://prntscr.com/mao7jz
GUI version is looking awesome and GUI version hv export function ?

**Comment by riazXrazor** [comment]
select a course n video resolution , then the export will be generated.

**Comment by vikasnewports** [comment]
@riazXrazor  I got your point when I start to download a single course from direct url e.g udl -u -p course_url ... thn it download the course and create a tmp folder and Json file which contains all the videos links...
but when I tried this .. ( udl -u -p -e) it show me my courses and when I select a course it stuck see screen shot http://prntscr.com/mb6h0h
I want to download the list of my all joined courses i hope you are understanding my question
