### ISSUE TITLE
Don't create a separate folder for each video

### ISSUE THREAD

**Issue by mriverodorta** [riazXrazor/udemy-dl#43]
Every time i download a course, the downloader creates a folder for each video, there should be an option to download the videos form a section inside a section folder not ins a section folder->name of the video file folder->name of the video file.mp4
Take a look.

![dir](https://user-images.githubusercontent.com/5642941/50564434-b3790480-0cd9-11e9-90e6-e19e87a26c4b.png)

**Comment by riazXrazor** [comment]
Hi @mriverodorta, hmm i did this coz some course vids contains some materials with the vid too, so to make it general and organized i took an approach like this.

**Comment by mriverodorta** [comment]
hi @riazXrazor, it would be nice to have a flag to use a different behavior, like a --no-folders if the code base allows it. Thanks

**Comment by riazXrazor** [comment]
@mriverodorta plz update to latest version, i hv removed folder creation, creating only if there is a subtitle.

**Comment by mriverodorta** [comment]
thank you, the update worked like a charm.
