### ISSUE TITLE
1080p videos = Unknown video resolution

### ISSUE THREAD

**Issue by rla999** [riazXrazor/udemy-dl#48]
Enter your Udemy username : [REDACTED]
? Enter your password: *****************
? Select a course to download: 1 ) The Web Developer Bootcamp
? Select the maximum video resolution to download: 1080
  ◜ Initializing, please wait...
◞ Initializing, please wait...          Unknown video resolution

I know for a fact that 1080p videos exist for that course when I view it on the Udemy site.
https://www.udemy.com/the-web-developer-bootcamp/

I know this tool can download 720 fine but I want 1080 downloaded if possible. Maybe Udemy changed their algorithm?

**Comment by riazXrazor** [comment]
Ya may be I'll look into it.

**Comment by riazXrazor** [comment]
Hi, pushed a fix for it, try with the latest version 1.0.1
