### ISSUE TITLE
Feature request: An option to download all from an account

### ISSUE THREAD

**Issue by prahaladbelavadi** [riazXrazor/udemy-dl#56]
I have courses on my Udemy account that I'd like to download without manually selecting each one. It would be a great option to have the default option to be set to download all downloadable courses from an account

**Comment by riazXrazor** [comment]
hmm, means u dont want to login each time right ?

**Comment by riazXrazor** [comment]
2.0 has this feature, u can try

**Comment by prahaladbelavadi** [comment]
@riazXrazor  I don't want to have to download each course manually. I assume the flag will log me in automatically. 

The user flow I'd like to propose is one where, on providing user credentials:
The downloader downloads all courses that have been bought by the account.
The user would not have to provide names of each course manually.

Technically, I presume the flow would be to query for a list of enrolled courses and loop through each item of the list to download them.  
This method would require the user to provide nothing but user credentials. 

What are your thoughts on this ?
