### ISSUE TITLE
getaddrinfo ENOTFOUND undefined

### ISSUE THREAD

**Issue by TebelloX** [riazXrazor/udemy-dl#60]
Enter your Udemy username: (node:29319) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
*******@gmail.com
Enter your password: ********
Authencating... done
getaddrinfo ENOTFOUND undefined
c4r24s5% 

I'm facing this problem after helplessly trying to use the service. Immediately after entering correct credentials and getting "Authenticating...done" in the terminal, I get "getaddrinfo ENOTFOUND undefined" and then I am not able to anything else after that. 

I am using Mac OS Mojave.

**Comment by riazXrazor** [comment]
This probably due to net connection, try installing the latest version n
try again.

**Comment by TebelloX** [comment]
Okay thanks. I have updated to the latest but I still get the same result unfortunately.

**Comment by eugmill** [comment]
@TebelloX I had the same issue when trying to use the global npm package. Pulling down the project and running locally worked for me.
