### ISSUE TITLE
Error could not fetch courses

### ISSUE THREAD

**Issue by bhanuuday** [riazXrazor/udemy-dl#64]
I have tried to download but getting the error "could not fetch courses".
![InkedScreenShot_20191127201247_LI](https://user-images.githubusercontent.com/11804995/69733016-aca97a80-1152-11ea-9cf6-eccacc46c5cb.jpg)

**Comment by hehrhart** [comment]
Error in `src.core.js` [_fetchCourses](https://github.com/riazXrazor/udemy-dl/blob/master/src/lib/core.js#L408) function. Callback is not defined in case where next is not null.

**Comment by sunnyparekh** [comment]
Solution?

**Comment by riazXrazor** [comment]
ur using the latest version??

**Comment by sunnyparekh** [comment]
Yes

**Comment by tejeshwar-p** [comment]
I get error after logging in and trying to fetch courses. I even tried to reset and using the latest version. Can it be fixed? Please find my attached screenshot.
![udemy-dl error](https://user-images.githubusercontent.com/13045329/74606830-97147300-50f9-11ea-8e0c-4cc69c5080cd.PNG)

**Comment by riazXrazor** [comment]
Hmmm issue might be somthing else, will hv to debug, i was able to login n fetch courses
![image](https://user-images.githubusercontent.com/13194363/74640089-07bc9d80-5195-11ea-817e-7c5745b26f67.png)

**Comment by ccataldo345** [comment]
I still have the same issue, "Error could not fetch courses".
Any solution please?

**Comment by tejeshwar-p** [comment]
> 
> 
> I still have the same issue, "Error could not fetch courses".
> Any solution please?

If you are using Udemy business account then it has different way to login. In my case I was using business account and tried to login as normal user which is why I faced that issue.

**Comment by ccataldo345** [comment]
> > I still have the same issue, "Error could not fetch courses".
> > Any solution please?
> 
> If you are using Udemy business account then it has different way to login. In my case I was using business account and tried to login as normal user which is why I faced that issue.  

Nope, I am using a normal account. And btw, something changed again, can not even login now.
  
```
https://www.udemy.com/join/login-popup/  
Authencating... done  
Forbidden
```
